"""Introspection: generates an ENGLISH textual report from internal variables.

FUNCTIONAL NOTE
---------------
This module emits templated English text describing the agent's current internal
variables across the cycle stages (perceive, attend, predict, intend, why,
remember, self-state). The text is GENERATED FROM STATE and is explicitly framed
as such: it is not, and must not be read as, evidence of subjective experience.
The agent is not conscious, sentient, or alive. Every report carries the
canonical functional-simulation disclaimer.
"""
from __future__ import annotations

from schemas.models import (
    ActionDecision,
    AttentionSchemaState,
    EmotionState,
    IntegrationState,
    IntrospectionReport,
    MemoryRecord,
    MetacognitiveState,
    Observation,
    Prediction,
    SalientItem,
    SelfModelState,
    WorkspaceState,
)

# Canonical disclaimer (French) — kept verbatim per project contract.
DISCLAIMER_FR = (
    "Simulation fonctionnelle de processus associes a la conscience. "
    "L'agent n'est ni conscient, ni sentient, ni vivant. Les rapports "
    "introspectifs sont des textes generes a partir de variables internes et "
    "ne constituent pas une preuve d'experience subjective."
)

# Canonical disclaimer (English) — user-facing default.
DISCLAIMER_EN = (
    "Functional simulation of processes associated with consciousness. "
    "The agent is not conscious, sentient, or alive. Introspective reports "
    "are text generated from internal variables and do not constitute "
    "evidence of subjective experience."
)


class Introspection:
    """Produces an :class:`IntrospectionReport` from current cycle variables."""

    def generate(
        self,
        *,
        observation: Observation,
        salient: list[SalientItem],
        prediction: Prediction,
        decision: ActionDecision,
        memory_matches: list[MemoryRecord],
        self_model: SelfModelState,
        emotion: EmotionState,
        workspace: WorkspaceState | None = None,
        attention_schema: AttentionSchemaState | None = None,
        metacognition: MetacognitiveState | None = None,
        integration: IntegrationState | None = None,
    ) -> IntrospectionReport:
        """Build a templated English introspection report from the variables.

        Each field is phrased as a description of internal variables (e.g.
        "My perception variables indicate...") rather than as lived
        experience, making the generated-from-state framing explicit.

        When the v2 consciousness-architecture sub-states are supplied, the
        report is augmented with sentences describing what reached global access
        (GWT), the attention-schema self-attribution (AST), the higher-order
        report (HOT), and the Phi-proxy / free-energy figures (IIT/active
        inference). All such text remains explicitly framed as generated by the
        AST/HOT mechanisms from internal variables, never as lived experience.
        """
        n_visible = len(observation.visible)
        perceive = (
            f"My perception variables indicate {n_visible} object(s) within a "
            f"radius of {observation.radius} around the position "
            f"({observation.agent_x}, {observation.agent_y}); recorded internal "
            f"energy: {observation.agent_energy:.1f}."
        )

        if salient:
            top = salient[0]
            p = top.percept
            attend = (
                f"The attentional filter retains {len(salient)} element(s). "
                f"The most salient item is object {p.object_id} ({p.kind}, "
                f"saliency {top.saliency:.2f}, distance {p.distance:.1f})."
            )
        else:
            attend = (
                "No element exceeds the attentional threshold at this tick; "
                "the focalization variable is null."
            )

        # GWT: what reached global access this tick.
        if workspace is not None:
            if workspace.ignited:
                attend += (
                    f" Global access (GWT): the content '{workspace.winner_content}' "
                    f"(source '{workspace.winner_source}') crossed the ignition "
                    f"threshold ({workspace.threshold:.2f}) and is broadcast "
                    f"globally (strength {workspace.broadcast_strength:.2f})."
                )
            else:
                attend += (
                    " Global access (GWT): no content crossed the ignition "
                    f"threshold ({workspace.threshold:.2f}); subliminal influence "
                    f"(strength {workspace.broadcast_strength:.2f})."
                )
        # AST: the attention-schema self-attribution (source of the claim).
        if attention_schema is not None:
            attend += f" {attention_schema.attributed_self}"

        target_txt = (
            f" on the target {prediction.target_id}"
            if prediction.target_id is not None
            else ""
        )
        predict = (
            f"The world model predicts for the action '{prediction.action.value}'"
            f"{target_txt}: energy delta {prediction.expected_energy_delta:.2f}, "
            f"danger {prediction.expected_danger:.2f}, novelty "
            f"{prediction.expected_novelty:.2f}, goal-progress "
            f"{prediction.expected_goal_progress:.2f} (uncertainty "
            f"{prediction.uncertainty:.2f})."
        )

        intend = (
            f"The decision variable selects the action "
            f"'{decision.action.value}'"
            + (
                f" targeting object {decision.target_id}"
                if decision.target_id is not None
                else ""
            )
            + f" with a confidence of {decision.confidence:.2f}."
        )

        why = f"Rationale generated from state: {decision.rationale}"

        if memory_matches:
            ids = ", ".join(str(r.id) for r in memory_matches)
            remember = (
                f"Episodic retrieval returns {len(memory_matches)} "
                f"similar record(s) (identifiers: {ids}). "
                "These are stored data, not lived memories."
            )
        else:
            remember = (
                "Episodic retrieval returns no similar record "
                "for the current context."
            )

        self_state = (
            f"My self-model ({self_model.identity}) indicates: energy "
            f"{self_model.energy:.1f}, confidence {self_model.confidence:.2f}, "
            f"mood {self_model.mood:.2f}, coherence {self_model.coherence:.2f}. "
            f"Functional affect: fear {emotion.fear:.2f}, curiosity "
            f"{emotion.curiosity:.2f}, satisfaction {emotion.satisfaction:.2f}, "
            f"fatigue {emotion.fatigue:.2f}, confusion {emotion.confusion:.2f}."
        )

        # HOT: higher-order report about the first-order state.
        if metacognition is not None:
            self_state += f" {metacognition.higher_order_report}"
        # IIT proxy + active inference free energy figures.
        if integration is not None:
            self_state += (
                f" Integrated information (Phi proxy, heuristic, NOT an IIT "
                f"measure): {integration.phi_proxy:.2f} "
                f"(differentiation {integration.differentiation:.2f}, integration "
                f"{integration.integration:.2f}, {integration.n_elements} elements)."
            )
        self_state += (
            f" Expected free energy of the chosen action (active inference): "
            f"{prediction.expected_free_energy:.2f}."
        )

        return IntrospectionReport(
            tick=int(observation.tick),
            disclaimer=DISCLAIMER_EN,
            perceive=perceive,
            attend=attend,
            predict=predict,
            intend=intend,
            why=why,
            remember=remember,
            self_state=self_state,
        )
